name: login_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'  # It's good practice to specify a range

dependencies:
  flutter:
    sdk: flutter

  # Your existing dependencies
  cupertino_icons: ^1.0.8

  # Firebase
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.3
  firebase_core: ^4.2.0
  sign_in_with_apple: ^7.0.1
  google_sign_in: ^7.2.0

  #BLoC
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Add these for Freezed
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  rxdart: ^0.28.0
  flutter_lints: ^6.0.0

  # For code generation
  build_runner: ^2.9.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1

  melos: ^6.3.3

  user_repository:
    path: packages/user_repository