// my_user_entity.dart

// These 'part' files will be generated by the build_runner
import 'package:freezed_annotation/freezed_annotation.dart';

part 'my_user_entity.freezed.dart';
part 'my_user_entity.g.dart';

@freezed
class MyUserEntity with _$MyUserEntity {
  // Make the constructor const
  const factory MyUserEntity({
    required String id,
    required String email,
    required String name,
    String? picture,
  }) = _MyUserEntity;

  // This factory constructor is the magic that replaces your fromDocument method
  factory MyUserEntity.fromJson(Map<String, dynamic> json) => _$MyUserEntityFromJson(json);
}
