name: user_repository
description: Dart package which manages the user.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7

  # Firebase
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.3
  firebase_core: ^4.2.0

 # Google Sign In
  google_sign_in: ^7.2.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
